export {default as Logo} from './logo'
export {default as NavBar} from './navbar'
export {default as Deposition} from './deposition'
export {default as Seal} from './seal'
export {default as Social} from './social'
export {default as ContactForm} from './contact-form'